CREATE TABLE microposts.user (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user_id VARCHAR(100) UNIQUE,
    user_name VARCHAR(100),
    user_pass VARCHAR(100),
    user_email VARCHAR(100) UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);